[package]
name = "super-auto-pets-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "super_auto_pets_ai"
path = "src/main.rs"